### ISSUE TITLE
Need only 1 change for mele f10 lite

### ISSUE THREAD

**Issue by eliazu** [sumotoy/MeleF10Pro_for_Win_XBMC#4]
hey
you are my last hope.
there is no way to identify in windows the "menu" except for your solution.
the problem is that your program (64 bit) opens a box when i click on the menu button that says:
"Windows title" inside the box, and "mele pro not connected" in the windows title...

is it possible you will make a change for this button will be remapped to any free combination?
if not, can you share the source code?

thank you very much.
![capture](https://cloud.githubusercontent.com/assets/13870102/15786075/4437c40e-29c3-11e6-9b00-290e76fb7fbf.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13870102/15786074/44360970-29c3-11e6-8566-98159e82e33a.PNG)

**Comment by sumotoy** [comment]
At the time I writed this soft Mele f10lite doesn't exists. It looks like is not recognized...
Have search the source code...

**Comment by eliazu** [comment]
your program is the only one that made any action for clicking on this button.
can you describe which code did you use for listening to the device input in the win development platform?

**Comment by sumotoy** [comment]
Have to look in my backups for the source code, don't remember now, maded it long time ago!
Actually I will do it with C++ and Visual Studio, but I haved used other system for this.
Let me find source code...

**Comment by sumotoy** [comment]
source upped.

**Comment by eliazu** [comment]
thank you!
